### PR TITLE
[d3d9] Fail GetRTData if src and dst have mismatching sizes

### LINKED ISSUE #3825: MySims (PC) Select Bug
A bug is causing the areas where you can click on your Sim’s clothing, hairstyle, facial features, building pieces while building homes, and the areas to paint walls, floors or building pieces to instead be located at the top middle of the screen, this also causes the game to be unplayable on new save games since you cannot progress the tutorial after entering build mode to create your house.

I figured I’d post this here since I’m not sure what is causing the bug, if it’s wine or DXVK.

I did see a post regarding the MySims Wii titles where the same issue occurred in Dolphin for a user, and supposedly, setting EFB Copies to RAM fixed the issue, which could mean it’s due to textures? I’m not entirely sure.

### Software information
MySims (PC)
Application Type: 32-Bit
Resolution: 1280x800
Fullscreen: Yes

### System information
- GPU: AMD AMD Custom GPU 0405 (vangogh, LLVM 15.0.7, DRM 3.54, 6.1.52-valve9-1-neptune-61)
- Driver: 4.6 (Compatibility Profile) Mesa 23.1.3 (git-58f7632462)
- Wine version: 8.0 (Proton Experimental)
- DXVK version: v2.3-28-geb806952d8d0da9

### ApiTrace files
https://drive.google.com/file/d/1JHTwm1POpFewKKkZr_YoMRJnwIIgatoQ/view?usp=drive_link

### Log files
[steam-15313046569196978176.zip](https://github.com/doitsujin/dxvk/files/14103354/steam-15313046569196978176.zip)
Sorry, I have to provide the proton log as a zip file due to the size of the log file, I’m not sure why it’s so large…

### PR DESCRIPTION
**Pull request by K0bin**
Fixes #3825

See the commit message.
This solves the problem according to Blisto. Pretty stupid.

### CODE REVIEW

File: src/d3d9/d3d9_device.cpp [hunk 1]
```diff
@@ -1037,6 +1037,13 @@ namespace dxvk {
     if (srcTexInfo->Desc()->Format != dstTexInfo->Desc()->Format)
       return D3DERR_INVALIDCALL;
 
+    D3DSURFACE_DESC srcSurfDesc;
+    D3DSURFACE_DESC dstSurfDesc;
+    src->GetDesc(&srcSurfDesc);
+    dst->GetDesc(&dstSurfDesc);
+    if (srcSurfDesc.Width != dstSurfDesc.Width || srcSurfDesc.Height != dstSurfDesc.Height)
```
Comment (Joshua-Ashton) [inline src/d3d9/d3d9_device.cpp:1044]: Just use `src->GetSurfaceExtent() != dst->GetSurfaceExtent()`. No need to get the descs.

**Review by Joshua-Ashton — CHANGES_REQUESTED** [review]
