### PR TITLE
D3D9: Fix fixed function sampler mask

### LINKED ISSUE #4338: [d3d9][regression] Ascension to the Throne black ground
In Ascension to the Throne the ground shows as black since commit https://github.com/doitsujin/dxvk/commit/5e48035e992d52c9862b2d2ef5ac1e92112cde90

### Software information
[Ascension to the Throne](https://store.steampowered.com/app/289200/Ascension_to_the_Throne/)

### System information
- GPU: RTX 4080
- Driver: 550.40.71
- Wine version: Proton Bleeding Edge
- DXVK version: https://github.com/doitsujin/dxvk/commit/5e48035e992d52c9862b2d2ef5ac1e92112cde90 and above

### Apitrace file(s)
https://drive.proton.me/urls/3N44WV93VR#SgaxJsDhNV0o

### PR DESCRIPTION
**Pull request by K0bin**
Fixes #4338

I also added a bunch of missing likely/unlikely.
I'd prefer it if @misyltoad could take a look as she can better review how common each of those is.

### CODE REVIEW

File: src/d3d9/d3d9_device.cpp [hunk 1]
```diff
@@ -6908,7 +6908,7 @@ namespace dxvk {
       const uint32_t buffersToUpload = m_activeVertexBuffersToUpload & usedBuffersMask;
       for (uint32_t bufferIdx : bit::BitMask(buffersToUpload)) {
         auto* vbo = GetCommonBuffer(m_state.vertexBuffers[bufferIdx].vertexBuffer);
-        if (vbo != nullptr && vbo->NeedsUpload())
+        if (likely(vbo != nullptr && vbo->NeedsUpload()))
```
Comment (misyltoad) [inline src/d3d9/d3d9_device.cpp:6911]: why is this likely?

Comment (K0bin) [reply src/d3d9/d3d9_device.cpp:6911]: Because we're inside the bit mask loop. Any 1 bit of that should also have NeedsUpload() set unless.

**Comment by misyltoad** [comment]
Good thing I don't play the oboe.
