### PR TITLE
Upload per-draw data for dynamic systemmem buffers

### LINKED ISSUE #1828: [D3D9] Blood Rayne
sags in places fps

### Software information
Blood Rayne, high settings.

### System information
- GPU: Radeon RX 590
- Driver: RADV ACO
- Wine version: Proton 5.0-10
- DXVK version: d3d8to9 + dxvk Master

### Apitrace file(s)
https://drive.google.com/file/d/13wN65c383z6tqdtn-y2gY75HNlfKgEhY/view?usp=sharing

### Log files
- d3d9.log: [rayne1_d3d9.log](https://github.com/doitsujin/dxvk/files/5577522/rayne1_d3d9.log)

### LINKED ISSUE #2375: Flammable Freddy - Bad performance
Flammable Freddy, a game made by a Youtuber I regularly watch, runs very poorly with DXVK and runs out of address space. The game is made with a game engine called Clickteam Fusion, I assume other games using it have the same issue.

The problem is that the game heavily relies on D3DLOCK_NOOVERWRITE when uploading data before every draw. The buffer is a vertex buffer in the systemmem pool with the usages D3DUSAGE_WRITEONLY | D3DUSAGE_DYNAMIC. DXVK ignores D3DLOCK_NOOVERWRITE for everything that isn't in D3DPOOL_DEFAULT, so we do a ton of copying and eventually run out of address space.

The game itself isn't really important but it highlights that we still havent gotten the D3DLOCK flags right.

### Software information
Flammable Freddy

### System information
- GPU: GTX 1070
- Driver: 495.44
- Wine version: 6.21
- DXVK version: 1.9.2 or PR 2364.

### Log files
- d3d9.log: Not useful.

### LINKED ISSUE #3755: [d3d9] Shank 2: performing worse than WineD3D
Shank 2 with DXVK is performing worse compared to WineD3D. To reproduce the slowdown you can just start a new campaign and play for less than 5 minutes (after leaving the initial vehicle, it's possible to notice). The fps is dropping below 40 sometimes (I'm using a 6700 XT with a 1080p resolution).

shank_2_perf

I've tried also the following DXVK properties: `d3d9.cachedDynamicBuffers=True` and `d3d9.floatEmulation=Strict` (but no gains)

### Software information
Game: Shank 2
Settings: maxed out at 1080p

### System information
- GPU: 6700 XT (12 Gb)
- CPU: Ryzen 7 5700 G (8c/16t)
- Driver: Mesa 23.3.1 and 23.2.1
- Wine version:  Proton 8.0-4 and 8.0-5 (RC)
- DXVK version: same versions used by the Proton builds

### Apitrace file(s)
- https://mega.nz/file/Qk0wRbhZ#bQeOlKnDJBNpwL8WYxg943ZIgqMrwKS5luJbh_2urUg

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
- [steam-102840.tar.gz](https://github.com/doitsujin/dxvk/files/13714474/steam-102840.tar.gz)

### PR DESCRIPTION
**Pull request by K0bin**
Fixes #3755
Fixes #2375
Fixes #1828

Every frame Shank 2 maps multiple >1MB buffers with SizeToLock = 0.
That means we cannot just upload a subset of the buffer but have to upload the entire buffer multiple times per frame.
Copying that much data around is slow and on top of that it exceeds our 16MB staging buffer budget which makes us stall until the GPU is done with the earlier staging data.
This is actually the first time I've seen a game blow that budget outside of loading screens.

This PR changes it so that draws that only use buffers with D3DPOOL_SYSTEMMEM + D3DUSAGE_DYNAMIC upload all required data before each draw similar to DrawPrimitiveUp/DrawIndexedPrimitiveUp.

This reduces the amount of data copied each frame in Shank 2 from >30MB to <1MB.

I assume D3D9 drivers (or the runtime) do something similar given that applications need to actually provide information about the accessed vertices for indexed draws (https://learn.microsoft.com/en-us/windows/win32/api/d3d9/nf-d3d9-idirect3ddevice9-drawindexedprimitive).

### CODE REVIEW

**Comment by K0bin** [comment]
@ Josh If you have any ideas how to make this a bit less ugly, I'm all ears.

**Comment by K0bin** [comment]
Nine turns SYSMEM + DYNAMIC into PIPE_STREAM buffers, I assume the underlying driver will then do something similar as this PR.

**Comment by K0bin** [comment]
I changed the PR so it does the dynamic upload for either vertex buffers or the index buffer even if the other one doesn't qualify for dynamic uploads.

Clickteam Fusion (used by Flammable Freddy) hits this case with a Usage=0 index buffer and a large Usage=Dynamic vertex buffer.

**Comment by Blisto91** [comment]
During testing it has been found that the PR causes BloodRayne: Terminal Cut to only render black. The game itself is d3d8 but this edition ships with a d3d8 dll that translates it to 9.

Apitrace that reproducea the issue.
https://drive.proton.me/urls/4KYCDGFQTW#_QB3an2qaYpl

File: src/d3d9/d3d9_device.cpp [hunk 1]
```diff
@@ -2615,7 +2615,22 @@ namespace dxvk {
     if (unlikely(!PrimitiveCount))
       return S_OK;
 
-    PrepareDraw(PrimitiveType);
+    bool dynamicSysmemVBOs = true;
```
Comment (Joshua-Ashton) [inline src/d3d9/d3d9_device.cpp:2618]: If every vbo is nullptr, this should be false to handle the case of Draws with 0 vertex buffers bound, right?

File: src/d3d9/d3d9_device.cpp [hunk 2]
```diff
@@ -2652,7 +2667,34 @@ namespace dxvk {
...
+    for (uint32_t i = 0; i < caps::MaxStreams && dynamicSysmemVBOs; i++) {
```
Comment (Joshua-Ashton) [inline src/d3d9/d3d9_device.cpp:2671]: Can we de-dupe this code between the two places?

File: src/d3d9/d3d9_device.cpp [hunk 3]
```diff
@@ -2652,7 +2667,34 @@ namespace dxvk {
...
+      auto* vbo = GetCommonBuffer(m_state.vertexBuffers[i].vertexBuffer);
+      dynamicSysmemVBOs &= vbo == nullptr || vbo->IsSysmemDynamic();
+    }
+    D3D9CommonBuffer* ibo = GetCommonBuffer(m_state.indices);
+    bool dynamicSysmemIBO = ibo->IsSysmemDynamic();
+
+    PrepareDraw(PrimitiveType, !dynamicSysmemVBOs, !dynamicSysmemIBO);
+
+    if (unlikely(dynamicSysmemVBOs || dynamicSysmemIBO)) {
```
Comment (Joshua-Ashton) [inline src/d3d9/d3d9_device.cpp:2680]: I don't really like this open-coded here, can we move it to PrepareDraw?

Comment (Joshua-Ashton) [reply src/d3d9/d3d9_device.cpp:2680]: Feel free to gate it behind some constexpr thing for indexed vs not.

**Comment by K0bin** [comment]
@Joshua-Ashton Updated it, pls give some feedback on the changes.

File: src/d3d9/d3d9_device.cpp [hunk 4]
```diff
@@ -5091,6 +5117,159 @@ namespace dxvk {
...
+        BaseVertexIndex = -FirstVertexIndex;
+      } else {
+        FirstVertexIndex = 0;
+      }
+    }
+
+    if (dynamicSysmemIBO) {
+      if (unlikely(iboUPBufferSize == 0)) {
+        EmitCs([
+          cIndexType = VK_INDEX_TYPE_UINT32
```
Comment (Joshua-Ashton) [inline src/d3d9/d3d9_device.cpp:5244]: why is this a capture?

File: src/d3d9/d3d9_device.cpp [hunk 5]
```diff
@@ -5091,6 +5117,159 @@ namespace dxvk {
     return D3D_OK;
   }
 
+  
+
+  void D3D9DeviceEx::UploadDynamicSysmemBuffers(
```
Comment (Joshua-Ashton) [inline src/d3d9/d3d9_device.cpp:5122]: Do we want to mark this as inline?

**Review by Joshua-Ashton — CHANGES_REQUESTED** [review]

File: src/d3d9/d3d9_device.cpp (hunk 5 above)
Comment (K0bin) [reply src/d3d9/d3d9_device.cpp:5122]: We could do that but we don't mark PrepareDraw as inline either.

File: src/d3d9/d3d9_device.cpp (hunk 4 above)
Comment (K0bin) [reply src/d3d9/d3d9_device.cpp:5244]: Yeah that's pretty stupid. :)

File: src/d3d9/d3d9_device.cpp (hunk 5 above)
Comment (Joshua-Ashton) [reply src/d3d9/d3d9_device.cpp:5122]: Ehh fair enough
