### PR TITLE
[d3d9] Fix issues with presentation

### LINKED ISSUE #1476: [d3d9] Evenicle - Crash to desktop at startup (wine) / Black screen (proton)
I was a bit hesitant at first to report the issue, the game being a H-game and all, but hey, these games also need some love, don't judge please :)

The issue is the following :

If I try running the game using proton;
- Using version 4.11, the game run properly.
- Using version 5.0.3, the game render as a black screen. I am still able to press the buttons from the main menu and do stuff, I am only unable to see what I am doing.

If I try running the game using the latest wine and DXVK
- I create a new wine prefix and then run setup_dxvk.sh install --symlink
- I cd into the game directory and run "wine Evenicle.exe".
- The game imediately crashes. I get the following backtrace from wine: 
[Evenicle-backtrace.txt](https://github.com/doitsujin/dxvk/files/4253107/Evenicle-backtrace.txt)

If I try running the game using the latest wine without DXVK
- I create a new wine prefix
- I cd into the game directory and run "wine Evenicle.exe".
- The game is working properly without issues

### Software information
Evenicle, steam build
https://store.steampowered.com/app/955560/Evenicle/

### System information
- GPU: Nvidia GTX 970
- Driver: Proprietary, 440.59
- Wine version: 5.2 (staging)
- DXVK version: 1.5.4-55-gfbf76e84+ (Last commit on master).

### Apitrace file(s)
[Evenicle.trace.zip](https://github.com/doitsujin/dxvk/files/4253085/Evenicle.trace.zip)

### Log files
- d3d9.log: [Evenicle_d3d9.log](https://github.com/doitsujin/dxvk/files/4253084/Evenicle_d3d9.log)

### LINKED ISSUE #1481: [d3d9] VenusBlood FRONTIER International (1189440) - Transitioning to Fullscreen will cause graphical flickering in the title's left pillarbox.
### Description:
Transitioning from Windowed to Fullscreen mode will cause graphical flickering to appear in the game's left pillarbox (title has a 4:3 aspect ration). The flicker appears to be remnants of the options menu.

Video: https://www.youtube.com/watch?v=22dym_0aC_I

This occurs on both Proton 5.0-3 and Windows using DXVK 1.5.4 or master (3587bcdb). b954ab88 is the last known functional build that allows you to transition to Fullscreen without any issues. Starting with caae5d18, the title will start rendering part of the in-game Settings menu inside the left pillarbox. 

The title does appear correctly when transitioning to Fullscreen with WineD3D and on native Windows. The issue also does not occur when launching directly into a Fullscreen state.

Please let me know if any additional information is required or if additional testing is needed.

### Notes:
- This game stops rendering new frames the moment you enter the settings menu.
- The in-game exit confirmation prompts is its own window (so... two DXVK_HUD).
- On Mesa if _RADV_DEBUG=zerovram_ is not set, the pillar-boxes will be filled with garbage data causing additional visual corruption:

| AMD Mesa w/o zerovram | Confirmation Prompt |
|-----------------------|:-------------------:|
|1189440 VenusBlood - Mesa|DXVK_HUD_PROMPT|

### Software information
VenusBlood FRONTIER International ([1189440](https://store.steampowered.com/app/1189440))

### System information
- OS: Ubuntu 18.04 / Windows 10 Pro 1909
- GPU: Radeon RX 580 / Nvidia GeForce GTX 970
- Driver: 20.1\~git2002270730.2b155b\~oibaf\~b / 440.59-0ubuntu0.18.04.1
- Wine version: Proton 5.0-3
- DXVK version: 1.5.4 / Master (3587bcdb)

### Apitrace file(s)
- https://drive.google.com/open?id=18horFsT5Ww6ZlH3qEqo9Pm0dR2uaEaGD

### Log files
- d3d9.log: [VBFI_d3d9.log](https://github.com/doitsujin/dxvk/files/4267324/VBFI_d3d9.log)

### Bisect w/ froggi.es builds:
master - 3587bcdb (❌)
1.5.4 - 2435c63 (❌)
1.5.2 - e242d7f (❌)
a57dc752 (❌)
eed57ed6 (❌)
caae5d18 (❌)
b954ab88 (✔️)
9e5e4c1c (✔️)
1.5.1 - 4308d9b (✔️)

### LINKED ISSUE #1554: Fantasy Grounds window painting regresssion in dxvk 1.5.2
When using dxvk, sections of the Fantasy Grounds main menu window and in-game tabletop window fail to draw correctly. They are often filled with black or with whatever was on that section of the screen previously. Moving the mouse around the window sometimes cause the incorrectly drawn areas to flicker.

These glitches are not present with dxvk 1.5.1, nor when dxvk is not used. They are present with dxvk 1.5.2 and 1.6.

As instructed, I captured an API trace without dxvk. The glitches did not appear in this case, of course, but I launched the program and moved the mouse in the same way that would cause the glitches if dxvk had been in use.

### Software information

Fantasy Grounds Classic 3.3.10

https://www.fantasygrounds.com/filelibrary/FGWebInstall.exe

### System information
- GPU: AMD RX 480
- Driver: amdgpu (linux kernel 5.3.0) + Valve's ACO Mesa fork from their PPA, which reports itself as "Mesa 20.0.0-devel (LLVM 8.0.0)"
- Wine version: tkg-protonified-4.6, from Lutris
- DXVK version: 1.6 and 1.5.2

### Apitrace file(s)

[FantasyGrounds.zip](https://github.com/doitsujin/dxvk/files/4440162/FantasyGrounds.zip)

### Log files

This log file was from a session that reproduced the glitches, not the apitrace session.

[FantasyGrounds_d3d9.log](https://github.com/doitsujin/dxvk/files/4440220/FantasyGrounds_d3d9.log)

### Screenshots

Startup screen without dxvk: (correct)

Screenshot_2020-04-03_12-23-47

Startup screen with dxvk: (incorrect; black areas)

Screenshot_2020-04-03_12-23-18

Screenshot_2020-04-03_12-23-34

Tabletop without dxvk: (correct)

Screenshot_2020-04-03_12-28-07

Tabletop with dxvk: (incorrect; black areas & leftovers)

Screenshot_2020-04-03_12-26-25
Screenshot_2020-04-03_12-27-56

### LINKED ISSUE #2240: [d3d9] - The Elder Scrolls® Online (306130) - Installer is blank when using DXVK 1.5.2 and newer.
### Description:
In **_The Elder Scrolls® Online_** (306130) the installer for the launcher (javaw.exe) is completely blank. Previously the installer assets would flicker enough for you to figure out how to proceed, but now it seems it always renders black (probably due to game update). This blocks the install flow unless the user specifically knows where to click. Based on a previous issue, I believe this is due to partial-presentation: https://github.com/doitsujin/dxvk/issues/1481

The previous behavior can be observed here: https://www.youtube.com/embed/UmaSjU4R_Lw?start=0&end=5

- Issue is not present on WineD3D.
- Issue occurs on both Nvidia and AMD GPUs.
- Issue occurs on both Proton 6.3-5 on all major DXVK versions since 1.5.2, including master (a2330b89d228f7bdd6ba5f415051345634c3cb7c). 

| WineD3D | DXVK 1.5.1 | DXVK - main
| ---- | ---- | ---- |
|WineD3D|DXVK-1 5 1|DXVK-a2330b8|

Please let me know if any additional information is required or if additional testing is needed.

### Software information
[The Elder Scrolls® Online](https://store.steampowered.com/app/306130/The_Elder_Scrolls_Online) (306130)

### System information
OS: Ubuntu 20.04
GPU: Radeon RX 5700 XT / Nvidia GeForce GTX 1060
Driver: 21.2.0\~kisak1\~f / 470.57.02-0ubuntu0.20.04.1
Wine version: Proton 6.3-5
DXVK version: 1.5.2 and up (including main - a2330b89d228f7bdd6ba5f415051345634c3cb7c)

### Apitrace file
- Link: https://drive.google.com/file/d/1uvHLN27sSfMirDjnxDgZv1GfmYOrwPic/view?usp=sharing

### Log files
d3d9.log: 
[javaw_d3d9.log](https://github.com/doitsujin/dxvk/files/6977969/javaw_d3d9.log)

### LINKED ISSUE #2456: [D3D9] Halo CE SPV3 Installer / Launcher Flickering UI
To reproduce this manually without a trace these steps need to be followed:

1. Create a clean wine prefix: `WINEPREFIX=$PWD/pfx64 winecfg`
2. Run `WINEPREFIX=$PWD/pfx64 winetricks -q dotnet461 mfc42 arial dxvk` (dotnet461 and arial are needed to make the installer / launcher run; mfc42 is required for Halo CE)
3. `cd` to wherever the SPV3 installer is, if not already in that directory
4. `WINEPREFIX=<path-to-the-prefix>/pfx64 wine start ./spv3.exe`
5. **At this point, the rendering issue should reveal itself** (since the launcher and the installer seem to be the same executable - see below)
6. The installer expects a Halo CE installation but only permits the user to show detection of it if the original CE installer was used or if it's a running Steam process; [the easiest way to do this is to just run the original installer](https://web.archive.org/web/20200104212910/http://dl.halomaps.org/dl.cfm?fid=410&f=halocesetup%255Fen%255F1%252E00%252Eexe&S=3&h=9E43C199C9D65B09F6BFA5E49EC83421) and gather the necessary information to install oneself* (running Steam properly in Wine is far more difficult)
7. Once this is done, the SPV3 installer will permit the user to install but will falsely claim not to have enough storage space if you try to move the default install location; if you wish to change it, the only option at the moment is to use symlinks to manipulate where it goes
8. After this is done, it will prompt the user to install OpenSauce (provided with the installer) to the game directory
9. Now, the issue can once again be encountered with the launcher by running it: `cd` to the game directory and run `WINEPREFIX=<path-to-the-prefix>/pfx64 wine start ./spv3.exe`

-----

- The trace(s) I collected are only a couple megabytes so I don't know how valuable they are
- In addition, while I was attempting to trace the issue, it doesn't occur with WineD3D; I'm only able to experience this issue when DXVK is installed
- I've had this issue for a long time with SPV3's installer / launcher across two Nvidia GPUs (namely the 1060 Max-Q and the 2080 Ti) and many of Nvidia's driver versions

### Software information

- Name of the Game Launcher: `spv3.exe`
- Installer used: https://www.moddb.com/mods/spv3-for-halo-ce/downloads/spv330-release
- SHA256 of the Installer: `6c18d9a089ed17a764e9e56ca52764358ef3f26c4f2f9022b68a1df5e35a5089`
- SHA256 of the Launcher: `6c18d9a089ed17a764e9e56ca52764358ef3f26c4f2f9022b68a1df5e35a5089` (They seem to be the same executable? - It seems to "install" itself into the game directory)

The installer / launcher is a 64-bit .NET 4.6.1 application, so I find that DXVK's behavior / influence on it (given that it's not actually a game) is very strange.

### System information
- **GPU:** Nvidia RTX 2080 Ti
- **Driver:** 510.39.01
- **Wine version:** vanilla 7.0
- **DXVK version:** 1.9.3

### Apitrace file(s)
[spv3 installer trace.tar.gz](https://github.com/doitsujin/dxvk/files/7928343/spv3.installer.trace.tar.gz)
[spv3 launcher trace.tar.gz](https://github.com/doitsujin/dxvk/files/7928178/spv3.launcher.trace.tar.gz)

### Log files
- d3d9.log: Not available
- d3d11.log: Not available
- dxgi.log: Not available

(None were produced in the tracing process)

### LINKED ISSUE #2542: black windows in dotnet applications
try using the visual studio installer (or the reshade installer) with wine 7.4, it renders fine with wined3d and it doesn't render fine with dxvk, with dxvk, the window is black unless you move you mouse in which case the portion of ui element you are hovering over reveals itself and turns the rest of the window black. 
image

the easy solution to this would be add some env variable that disables dxvk or the tougher one, which is patching dxvk

### LINKED ISSUE #2568: Return of Reckoning Hitching.
Hi, I understand that this is probably not designed specifically for an old game from 2009. However the RoR community has recently been looking at your work and attempting to utilise it to solve performance issues in such an old and poorly optimised game. So far we've experimented around with your proxy and it's boosted performance. However we've been encountering 'Hitching' issues where frame times go from between 6-12ms and spike randomly up to anywhere between 200-400ms. Do you know of any way this could be minimised or reduced utilising your proxy?

Thanks.
htiching_LI (2)

### LINKED ISSUE #2732: ME3Tweaks Mod Manager doesn't render UI correctly
ME3Tweaks Mod Manager, the mod manager for the Mass Effect saga, has problems rendering the UI with DXVK: it's completely black, but when moving the mouse in certain parts, sometimes the part of the UI the mouse is pointing at will briefly flash.

### Software information
The program can be downloaded here: https://github.com/ME3Tweaks/ME3TweaksModManager/releases/download/7.0.6.124/ME3TweaksModManagerExtractor_7.0.6.124.exe.
It needs to be executed to install it, then you can just launch the extracted file to reproduce the issue. 
(The latest version of the program doesn't work on Wine yet: [here](https://bugs.winehq.org/show_bug.cgi?id=53379), and [here](https://github.com/ME3Tweaks/ME3TweaksModManager/issues/299)).

### System information
- GPU: AMD Vega 6 (Ryzen 4500U)
- Driver: Mesa 22.1.1 (RADV)
- Wine version: 7.13
- DXVK version: 1.10.2

### Apitrace file(s)
The program just has to be opened to reproduce the issue, so the trace is small.
[ME3TweaksModManager.trace.zip](https://github.com/doitsujin/dxvk/files/9135564/ME3TweaksModManager.trace.zip) (Taken with WineD3D)

### Log files
[ME3TweaksModManager_d3d9.log](https://github.com/doitsujin/dxvk/files/9135594/ME3TweaksModManager_d3d9.log)

### LINKED ISSUE #2749: D3D9 Partial Presentation Mega-issue
Made to consolidate the other issues which concern the lack of partial presentation in dxvk.

This issue most commonly presents itself as the application being mostly black except for any element that changes look or redraws when hovered over with the mouse. Like a button that has a highlight when the mouse cursor is on it

<details>
  <summary>Example screenshots</summary>

Return of Reckoning launcher  

Screenshot_20220723_193300
Screenshot_20220723_193614
</details>

It is most common in various game launchers and wpf apps. A few games might use it too.
It can usually be worked around in dxvk by setting `d3d9.shaderModel = 1` which have been added in the past into dxvk for a few launchers.
If set in a local config usually you'll only want this to affect the launcher itself. Which can be done like below for a specific exe in `dxvk.conf`
```
[RoRLauncher.exe]
d3d9.shaderModel = 1
```

Tho setting `d3d9.shaderModel = 1` is not always a desirable solution since in some cases the app might become very sluggish if it falls back on software rendering or if it's unpacked into a temporary folder with a generic name where a config option can't reliably catch it.
Setting it for every app thrown this way is probably also not a welcome solution.

Concerned issues:
https://github.com/doitsujin/dxvk/issues/2732
https://github.com/doitsujin/dxvk/issues/2240
https://github.com/doitsujin/dxvk/issues/2568 (Part of issue)
https://github.com/doitsujin/dxvk/issues/2278
https://github.com/doitsujin/dxvk/issues/1476
https://github.com/doitsujin/dxvk/issues/2334
https://github.com/doitsujin/dxvk/issues/1481 (Maybe?)
https://github.com/doitsujin/dxvk/issues/2456
https://github.com/doitsujin/dxvk/issues/2542
https://github.com/doitsujin/dxvk/issues/2860 (Likely)
https://github.com/doitsujin/dxvk/issues/3005
https://github.com/doitsujin/dxvk/issues/3116 (Likely)
https://github.com/doitsujin/dxvk/issues/3208

### LINKED ISSUE #2756: [d3d9] Tametsi (Steam appid 709920) launcher is rendered black
That works fine with wined3d.

I looked at that a bit and I see two issues here. Attaching PoC hack (which I am not considering to be really correct, for illustration purposes only) which lets the launcher to render normally.

[poc.txt](https://github.com/doitsujin/dxvk/files/9193983/poc.txt)

This is java game which is using Java AWT (awt.dll) for drawing.

0. The game creates a swapchain with ID3DDevice9::CreateAdditionalSwapChainEx() with D3DSWAPEFFECT_COPY and BackBuffer of 1. Then, it gets the backbuffer from the swapchain just once and uses it somehow.

1. The game calls Present with source rect (0,0)-(557,584) and destination rectangle (-3,-22)-(554,562). It looks like nothing is ever presented with such a destination rectangle. I guess it is maybe because it violates VUID-VkDisplayPresentInfoKHR-dstRect-01258 but I didn't check in details. Adjusting the rect as in the attached patch (avoiding negative coordinates) fixes this part. That adjustment is of course incorrect for a general case but is probably correct for this case where there is no stretch, just shift.

2. With 1. worked around the launcher renders the first frame correctly but quickly goes black again.  In fact, it renders black each other frame and another one is correct. It does a few presents one after another and settles on the unfortunate black one. It seems to me that the issue here that AWT depends on D3DSWAPEFFECT_COPY to really keep the backbuffer contents untouched on Present. Another patch of the hack workarounds that part and makes it always render notmally.

### LINKED ISSUE #2915: [d3d9] Sword and Fairy 4 (1621680) black screen or flickering
That works fine on native WIndows or with wined3d (the issue is reproducible with dxvk on Windows as well).

It seems to me that the culprit is that the game always calls Present() twice (one after another immediately). The game has single swapchain with one backbuffer and D3DSWAPEFFECT_DISCARD. I guess that always results in the image copy on Windows and wined3d but with dxvk two images get swapped twice and correct image present is always followed by black image present which never gets rendered to.

### LINKED ISSUE #3005: The Infectious Madness of Doctor Dekker flickers
Intro sequence flickers like mad. Haven't tested more.

### Software information
https://store.steampowered.com/app/545540/The_Infectious_Madness_of_Doctor_Dekker/

### System information
- GPU: AMD RADV POLARIS10 (aka RX480)
- Driver: Mesa 22.0.5
- Wine version: wine-6.0.3 (Ubuntu 6.0.3~repack-1)
- DXVK version: v1.10.3

### Apitrace file(s)
[timodd_trimmed_packed.zip](https://github.com/doitsujin/dxvk/files/9844203/timodd_trimmed_packed.zip)

### Log files
[timodd_d3d9.log](https://github.com/doitsujin/dxvk/files/9844204/timodd_d3d9.log)

### LINKED ISSUE #3141: Fruit of Grisaia flickering
Please describe your issue as accurately as possible.
The game display flickering black box
If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Name of the game, settings used etc.
Fruit of Grisaia
### System information
- GPU: Intel iGPU
- Driver: Mesa 22.0.5
- Wine version: 8.0-rc1
- DXVK version: 2.0

### Apitrace file(s)

> The file should have the size of at least a few hundred megabytes (or at least one hundred if the game is very simple), quite often it's a few gigabytes

I cant do that because my internet speed is slow and i dont really know how do that

### Log files
- d3d9.log: 
[grisaia_d3d9.log](https://github.com/doitsujin/dxvk/files/10265860/grisaia_d3d9.log)

- d3d11.log:
- dxgi.log:
[grisaia_dxgi.log](https://github.com/doitsujin/dxvk/files/10265863/grisaia_dxgi.log)

### LINKED ISSUE #3206: [D3D9] Incorrectly Rendered Loading Progress Bar in DuLuDuBi Star
### Software information
DuLuDuBi Star (Non-Steam)
Game can be found [here](https://archive.org/details/duludubistar_202007).

### Running the Game
Needs `LC_ALL=zh_CN` set to work, else it crashes.
Would recommend renaming the game executable to something more readable.
Locale emulator is not compatible with Wine.

### System information
 - Steam Deck
 - Driver: Mesa 22.2.0 (git-17e5312102)
 - Wine version: Wine `lutris-fshack-7.2-x86_64`
 - DXVK version: V1.10.3 (Still happens on master)

### Apitrace file(s)
[game.trace.zip](https://github.com/doitsujin/dxvk/files/10473643/game.trace.zip)
(I nested a `.7z` inside of a `.zip` to cheat GitHub)

### Log files
[game_d3d9.log](https://github.com/doitsujin/dxvk/files/10473637/game_d3d9.log)
[game_dxgi.log](https://github.com/doitsujin/dxvk/files/10473638/game_dxgi.log)

### Screenshots
Screenshot 2023-01-21 19-46-31
Screenshot 2023-01-21 19-46-36

### Correct Behavior
image

### Notes
This could potentially be annoying to test, because after enough times of launching before a restart, this specific loading screen stops showing up because it all loads faster.

### LINKED ISSUE #3208: [d3d9] Koko kara Natsu no Innocence! (ここから夏のイノセンス！) black square glitch
Appears in main menu after hovering the mouse over menu items.
image

Wined3d seems to work fine.

### Software information
Trial version can be downloaded at https://www.getchu.com/soft.phtml?id=853845&gc=gc
Note that due to some bug in Wine, `GameData/movie.int` file must be deleted in order for the game to start.

### System information
- GPU: AMD Radeon RX 5500 XT
- Driver: MESA 22.3.3
- Wine version: 8.0-rc5
- DXVK version: 2.0

### Apitrace file(s)
- https://mega.nz/file/8rR0STZD#mJq3Dwcz7UKlGqt4VbBUoB_ZNGMALRWyDq_iKbYhT3M

### Log files
- d3d9.log: [cs2_d3d9.log](https://github.com/doitsujin/dxvk/files/10482905/cs2_d3d9.log)
- dxgi.log: empty

### LINKED ISSUE #3238: [d3d9] Zwei: The Ilvard Insurrection - constant flickering
The game constantly flickers on each frame. The flickering is fixed either by setting `d3d9.noExplicitFrontBuffer = True` or by using #2967. A d3d8 executable is also shipped with the game (ZWEI2P.exe) and is affected by the same problem.

I'll keep this open for tracking until the above PR is merged under some form ideally.

### Software information
Zwei: The Ilvard Insurrection

### System information
- GPU: RTX 3060
- Driver: 525.78.01
- Wine version: 7.22 Staging
- DXVK version: 2.1

### Apitrace file(s)
[ZWEI2PDX9.trace.tar.xz](https://drive.google.com/file/d/1P_PvYVK0iJEHRnTv-R8HZOOQIrhukFti/view?usp=share_link)

### Log files
- d3d9.log: [ZWEI2PDX9_d3d9.log](https://github.com/doitsujin/dxvk/files/10660800/ZWEI2PDX9_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

### LINKED ISSUE #3250: Zusi 3 (1040730) has broken cab images
Rendering of cabs in the simulator is broken on DXVK (works in WineD3D) .

### Software information
Zusi 3 (1040730) - defaults

### System information
- GPU: Nvidia 1660ti
- Driver: 528.85
- Wine version: 7 and 8 (Proton 7 and 8-alpha)
- DXVK version: 2.1

### Apitrace file(s)
https://drive.google.com/file/d/1aApV8a9l5xFtqHEe8EyGdkAJvLOrxDhN/view?usp=share_link

### Log files
- d3d9.log: [ZusiSim.64_d3d9.log](https://github.com/doitsujin/dxvk/files/10716697/ZusiSim.64_d3d9.log)

### PR DESCRIPTION
**Pull request by K0bin**
- Do GDI blit for SWAPEFFECT_COPY_VSYNC too (which is missing from the mingw headers on my system)
- Dont swap buffers when using SWAPEFFECT_COPY

~~- Blit the backbuffer contents into the frontbuffer, so GetFrontBufferData returns the expected data~~
~~- Replace `noExplicitFrontBuffer` with that frontbuffer blit (this needs testing)~~

- Dont create an additional front buffer for SWAPEFFECT_COPY and windowed SWAPEFFECT_DISCARD with 1 backbuffer. The latter behaves identical to SWAPEFFECT_COPY in my testing, it even supports partial presentation.
- In those cases, GetFrontBufferData will just return the contents of the backbuffer. That's technically wrong ofc but I don't think adding in another blit in windowed mode is worth it. It's only wrong for SWAPEFFECT_COPY and DISCARD in windowed mode. Fullscreen SWAPEFFECT_COPY is probably very rare because that kind of defeats the purpose as partial presentation doesn't work in fullscreen. GetFrontBufferData was broken in windowed mode anyway because Windows takes a screenshot of the entire screen when you call it and we just used to return the contents of the front buffer.

Fixes #2732
Fixes #2240
Fixes #2568
Fixes #3238
Fixes #1476
Fixes #1481
Fixes #2456
Fixes #2542
Fixes #3005 
Fixes #3208
Fixes #3238
Fixes #3206
Fixes #3141
Fixes #3250 
Fixes #1554
Fixes #2756
Fixes #2915

Closes #2749

### CODE REVIEW

File: src/d3d9/d3d9_swapchain.cpp [hunk 1]
```diff
@@ -727,8 +737,23 @@ namespace dxvk {
...
 
     // Retrieve the image and image view to present
-    auto swapImage = m_backBuffers[0]->GetCommonTexture()->GetImage();
-    auto swapImageView = m_backBuffers[0]->GetImageView(false);
+    Rc<DxvkImage> swapImage;
+    Rc<DxvkImageView> swapImageView;
+
+    const bool copyToFrontbuffer = m_presentParams.SwapEffect == D3DSWAPEFFECT_COPY
+      || m_presentParams.SwapEffect == D3DSWAPEFFECT_COPY_VSYNC
+      || m_backBuffers.size() == 2;
```
Comment (Joshua-Ashton) [inline src/d3d9/d3d9_swapchain.cpp:745]: This m_backbuffers.size() == 2 thing seems sus. I guess its really because there is only one back buffer + one frontbuffer?

Comment (K0bin) [reply src/d3d9/d3d9_swapchain.cpp:745]: Yeah that's the idea.

Its something I noticed when looking at an apitrace of one of the games we enable noExplicitFrontbuffer for.

**Comment by pchome** [comment]
imho using const `swapEffectCopy` everywhere would be cleaner a bit
```c++
const bool swapEffectCopy = m_presentParams.SwapEffect == D3DSWAPEFFECT_COPY || m_presentParams.SwapEffect == D3DSWAPEFFECT_COPY_VSYNC;
```

File: src/d3d9/d3d9_swapchain.cpp (hunk 1 above)
Comment (Joshua-Ashton) [reply src/d3d9/d3d9_swapchain.cpp:745]: Wonder how many games inadvertently hit this though... Hmmm.

Comment (Joshua-Ashton) [reply src/d3d9/d3d9_swapchain.cpp:745]: What swap effect was the game using?

Comment (K0bin) [reply src/d3d9/d3d9_swapchain.cpp:745]: That's the fun part. SWAPEFFECT_DISCARD...

Comment (Joshua-Ashton) [reply src/d3d9/d3d9_swapchain.cpp:745]: Maybe our handling of frontbuffer is wrong and there really is only meant to be one backbuffer which is also the frontbuffer? Maybe only COPY has an implicit extra frontbuffer... idk.

**Comment by K0bin** [comment]
I wrote a [test application](https://github.com/doitsujin/dxvk-tests/pull/2) to figure out how this is supposed to behave:

```
FLIP + 5 buffers => shows front buffer
FLIP + 1 buffers => shows front buffer
DISCARD + 5 buffers => shows front buffer
DISCARD + 1 buffers => does not show front buffer
FLIPEX + 5 buffers => shows front buffer
FLIPEX + 1 buffers => shows front buffer

FLIP + 5 buffers + Fullscreen => shows front buffer
FLIP + 1 buffers + Fullscreen => shows front buffer
DISCARD + 5 buffers + Fullscreen => shows front buffer
DISCARD + 1 buffers + Fullscreen => shows front buffer
FLIPEX + 5 buffers => shows front buffer
FLIPEX + 1 buffers => shows front buffer

GetFrontBufferData takes a screenshot in windowed mode!
Otherwise works as expected.

Partial Present does not work in fullscreen mode.
Partial Present works for COPY and DISCARD + 1 buffer
```

File: src/d3d9/d3d9_swapchain.h [hunk 2]
```diff
@@ -197,6 +200,17 @@ namespace dxvk {
 
     std::string GetApiName();
 
+    const Com<D3D9Surface, false>& GetFrontBuffer() const {
+        return m_backBuffers.back();
+    }
+
+    const bool DoFrontbufferBlit() const {
```
Comment (DadSchoorse) [inline src/d3d9/d3d9_swapchain.h:207]: a bit of a nit, but const on a primitive return type doesn't make sense.

**Comment by w-flo** [comment]
> Replace `noExplicitFrontBuffer` with that frontbuffer blit (this needs testing)

FWIW, I tested Zusi 3 with your latest patches applied on top of master, and it seems to work without issues. :frog: Zusi 3 needed the noExplicitFrontBuffer config because it uses DISCARD swapeffect & 1 backbuffer. Thanks for working to get rid of that noExplicitFrontBuffer hack!

**Comment by arodland** [comment]
Tested FlexRadio SmartSDR, which is a WPF app that has absolutely horrible performance with regular wine and broken (mostly black) display with dxvk 2.1 and master.

This build makes it run just like it does on wined3d — visually correct, but near-unusably slow. I guess it was too much to hope for a magic fix :)

**Comment by Blisto91** [comment]
Yes this implementation is expected to be slow

**Comment by Blisto91** [comment]
Testing of front buffer issues and related
#3238 **Fixed**
#3206 **Fixed based on apitrace**
#3141 **Fixed**
#3250 **Fixed. Thanks** @CME42
#1554 **Fixed based on apitrace**

Honorable mention
#2756 **Fixed**

**Comment by Joshua-Ashton** [comment]
@K0bin Do you want to add all of these issues to your commit with a `Closes:` so we can have a super statisfying clean sweep? :-)

File: src/d3d9/d3d9_swapchain.cpp [hunk 3]
```diff
@@ -954,7 +961,7 @@ namespace dxvk {
     // creating a new one to free up resources
     DestroyBackBuffers();
 
-    int NumFrontBuffer = m_parent->GetOptions()->noExplicitFrontBuffer ? 0 : 1;
+    int NumFrontBuffer = !HasFrontBuffer() ? 0 : 1;
```
Comment (Joshua-Ashton) [inline src/d3d9/d3d9_swapchain.cpp:964]: Flip this so it's more readable please.

File: src/d3d9/d3d9_swapchain.h [hunk 4]
```diff
@@ -197,6 +198,17 @@ namespace dxvk {
...
     std::string GetApiName();
 
+    const Com<D3D9Surface, false>& GetFrontBuffer() const {
+      return m_backBuffers.back();
+    }
+
+    bool HasFrontBuffer() const {
+      // Tests show that SWAPEEFFECT_DISCARD + 1 backbuffer in windowed mode behaves identically to SWAPEFFECT_COPY
+      // For SWAPEFFECT_COPY we don't swap buffers but do another blit to the front buffer instead.
+      return m_presentParams.SwapEffect != D3DSWAPEFFECT_COPY
```
Comment (Joshua-Ashton) [inline src/d3d9/d3d9_swapchain.h:208]: Split into multiple if's so this is just easier to follow. This chain of logic is ough enough as it is.

**Review by Joshua-Ashton — CHANGES_REQUESTED** [review]
Minor nits.

**Comment by w-flo** [comment]
The very first bug report about the front buffer stuff might have been #1368, which this PR fixes properly instead of special-casing the workaround, so if you want to add it to the super long `Closes:` line :1st_place_medal: …

File: src/d3d9/d3d9_swapchain.h [hunk 5]
```diff
@@ -197,6 +198,24 @@ namespace dxvk {
 
     std::string GetApiName();
 
+    const Com<D3D9Surface, false>& GetFrontBuffer() const {
+      return m_backBuffers.back();
+    }
+
+    bool HasFrontBuffer() const {
+      if (m_presentParams.SwapEffect != D3DSWAPEFFECT_COPY)
+        return true;
```
Comment (pchome) [inline src/d3d9/d3d9_swapchain.h:207]: the statement has `&&`s in prev version, so should be
```cpp
      if (m_presentParams.SwapEffect == D3DSWAPEFFECT_COPY)
        return false;
```
and so on

Comment (Joshua-Ashton) [reply src/d3d9/d3d9_swapchain.h:207]: This

File: src/d3d9/d3d9_swapchain.h [hunk 6]
```diff
@@ -197,6 +198,24 @@ namespace dxvk {
 
     std::string GetApiName();
 
+    const Com<D3D9Surface, false>& GetFrontBuffer() const {
+      return m_backBuffers.back();
+    }
+
+    bool HasFrontBuffer() const {
+      if (m_presentParams.SwapEffect != D3DSWAPEFFECT_COPY)
```
Comment (PatrickvL) [inline src/d3d9/d3d9_swapchain.h:206]: Does `m_backBuffers.count` need to be above 1 too? Or does this function purely have to rely on `SwapEffect`?

Comment (K0bin) [reply src/d3d9/d3d9_swapchain.h]: This function is used to decide the size of `m_backBuffers`.
