### PR TITLE
[d3d9] Fixed function fix a bunch of wine tests with FF texture coord…

### LINKED ISSUE #3117: [d3d9] Phantasy Star Online Blue Burst missing textures with DXVK 2.0
Using an NVIDIA 3090 card with 526.98 driver (also happens with AMD cards), textures are missing when playing Phantasy Star Online Blue Burst in D3D9 mode.

We are utilizing D3D8to9 to elevate the game to D3D9, which works fine otherwise when you play vanilla Direct3D 9, but with DXVK we have missing texture problems.

In the screenshots attached, you can see that the Gol Dragon's monitors are blank (they flicker in real time), the laser panel in the Forest is blank, and the laser effect for doorways in CCA is completely missing.

Running this under straight Windows 11.
pso133146478979985817
pso133146478433965829
pso133146478242960077

I'm also uploading shots of how they SHOULD look like...

pso133146485348188990

pso133146485816619457
pso133146486079441087

Here's the log file from the game...

[psobb_d3d9.log](https://github.com/doitsujin/dxvk/files/10149113/psobb_d3d9.log)

### PR DESCRIPTION
**Pull request by K0bin**
Fixes #3117

Master:

> visual.c:28422: Driver string: "nvd3dum.dll"
visual.c:28423: Description string: "NVIDIA GeForce RTX 3090"
visual.c:28426: Device name string: "\\.\DISPLAY1"
visual.c:28428: Driver version 32767.65535.65535.65535
visual.c:5709: Test failed: quad 4 has color 00000000, expected 0x0033cc00
visual.c:5375: Test failed: D3DTTFF_COUNT3 | D3DTTFF_PROJECTED (draws non-projected) - top right: pixel (341, 211) has color ff000000, expected ffffffff.
visual.c:5375: Test failed: D3DTTFF_COUNT3 | D3DTTFF_PROJECTED (draws non-projected) - top right: pixel (341, 224) has color ff000000, expected ffffffff.
visual.c:5375: Test failed: D3DTTFF_COUNT3 | D3DTTFF_PROJECTED (draws non-projected) - top right: pixel (359, 211) has color ff000000, expected ffffffff.
visual.c:5375: Test failed: D3DTTFF_COUNT3 | D3DTTFF_PROJECTED (draws non-projected) - top right: pixel (359, 224) has color ff000000, expected ffffffff.
visual.c:5375: Test failed: D3DTTFF_PROJECTED (like COUNT3 | PROJECTED, texcoord has only 3 components) - bottom right: pixel (401, 361) has color ff000000, expected ffffffff.
visual.c:5375: Test failed: D3DTTFF_PROJECTED (like COUNT3 | PROJECTED, texcoord has only 3 components) - bottom right: pixel (401, 419) has color ff000000, expected ffffffff.
visual.c:5375: Test failed: D3DTTFF_PROJECTED (like COUNT3 | PROJECTED, texcoord has only 3 components) - bottom right: pixel (479, 361) has color ff000000, expected ffffffff.
visual.c:5375: Test failed: D3DTTFF_PROJECTED (like COUNT3 | PROJECTED, texcoord has only 3 components) - bottom right: pixel (479, 419) has color ff000000, expected ffffffff.
visual.c:5375: Test failed: D3DTTFF_COUNT1 (draws non-projected) - top right: pixel (341, 209) has color ffffffff, expected ff000000.
visual.c:5375: Test failed: D3DTTFF_COUNT1 (draws non-projected) - top right: pixel (341, 226) has color ffffffff, expected ff000000.
visual.c:5375: Test failed: D3DTTFF_COUNT1 (draws non-projected) - top right: pixel (359, 209) has color ffffffff, expected ff000000.
visual.c:5375: Test failed: D3DTTFF_COUNT1 (draws non-projected) - top right: pixel (359, 226) has color ffffffff, expected ff000000.
visual.c:5979: Test failed: quad 3 has color 00000000, expected 0x000000ff
visual.c:5981: Test failed: quad 4 has color 00000000, expected 0x00ffffff
visual.c:6068: Test failed: quad 3 has color 00ffffff, expected 0x00ff0000
45d4:visual: 460 tests executed (0 marked as todo, 0 as flaky, 16 failures), 0 skipped.

PR:

> visual.c:28422: Driver string: "nvd3dum.dll"
visual.c:28423: Description string: "NVIDIA GeForce RTX 3090"
visual.c:28426: Device name string: "\\.\DISPLAY1"
visual.c:28428: Driver version 32767.65535.65535.65535
a4d0:visual: 460 tests executed (0 marked as todo, 0 as flaky, 0 failures), 0 skipped.

I'd appreciate testing for regressions with:
~~#3293 (maybe @mrdeathjr28)~~ I still had the Apitrace of Coldfear and that is fine with the PR.
~~#3628 (@Blisto91)~~ I still had the Project Snowblind Apitrace and that also renders fine with the PR.
and Sims 2 (maybe @tannisroot)

### CODE REVIEW

**Comment by tannisroot** [comment]
Didn't see any regressions with this build in Sims 2 compared to 2.3.1.

File: src/d3d9/d3d9_constant_buffer.cpp [hunk 1]
```diff
@@ -146,7 +146,7 @@ namespace dxvk {
     // this applies to is so large that it will not matter.
     if (pDevice->CanSWVP()
      && ShaderStage == DxsoProgramType::VertexShader
-     && BufferType == DxsoConstantBuffers::VSConstantBuffer)
+     && (BufferType == DxsoConstantBuffers::VSConstantBuffer || BufferType == DxsoConstantBuffers::VSVertexBlendData))
```
Comment (doitsujin) [inline src/d3d9/d3d9_constant_buffer.cpp:149]: Looking at FF code, looks like vertex blend data is aways a storage buffer regardless of SWVP state.

I'm honestly in favour of unconditionally setting these as `UNIFORM | STORAGE` since drivers don't give a single shit about buffer usage flags anyway.

**Review by doitsujin — CHANGES_REQUESTED** [review]

File: src/d3d9/d3d9_constant_buffer.cpp (hunk 1 above)
Comment (K0bin) [reply src/d3d9/d3d9_constant_buffer.cpp]: Done.

**Comment by nolrinale** [comment]
Hello guys, i've tested the latest changes in PSOBB and the texture movement issue is fixed everywhere!!, theres a little detail with the refraction effect used in some monsters and for the splashing effects in water that seems to be a little bit off, not sure if its related to this texture fix but I've attached here a small video showcasing it.

@K0bin @doitsujin Moreover I wanted to mention that at least in the case of PSOBB, this game is actually a DX8 game not a DX9, so to be able to see the improvements i had to use d3d8to9 + your latest d3d9.dll as overrides not sure if that also might affect the outcome either

https://github.com/doitsujin/dxvk/assets/5244595/996ee404-53b8-46f0-9787-4a83c349e195

**Comment by K0bin** [comment]
@nolrinale Can you make an apitrace of the part that's not quite correct now?

**Comment by K0bin** [comment]
https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

@nolrinale

**Comment by nolrinale** [comment]
> https://github.com/doitsujin/dxvk/wiki/Using-Apitrace
> 
> @nolrinale
@K0bin 
I'm having troubles setting it up with your fixed d3d9.dll from the artifacts, and is not loading correctly for me. I'm getting the old versionw ithout the fixes instead....

However since you seem to have the game up and running from the previous main issue, create a Episode 2 Party and use the /warp command between areas 6-12 all these areas have water where you can splash around and see the issue

**Comment by nolrinale** [comment]
@K0bin I tried again to get you an apitrace of the affected area, but it looks like it wont get me a trace if I load the game with the d3d8to9's d3d8.dll.... and I require it to be able to elevate the game to DX9 to be able to see the fixed changes. 

If i load the game with the default d3d8.dll included in the apitrace package it does work and I can get a trace file but then I'm stuck with the old graphic issues, however in this specific case the water ripples and refraction works fine (minus the broken moving textures) so I guess there was a regression somewhere in this PR that affected this functionality.

**Comment by K0bin** [comment]
@nolrinale You don't have to use the latest fixed DXVK version. Apitrace records the D3D9 commands and those should be identical regardless of whether you use a DXVK build with my recent fixes or an older one.

**Comment by nolrinale** [comment]
@K0bin oh lol I had no clue about that!! well here you have it 
https://drive.google.com/file/d/1UEU3vOvYtv4FbaFd7TFeebuBnnvP2jH8/view?usp=sharing
The recording goes up to a little debug room at the end with lots of water where im walking in circles showing you the effect

**Comment by K0bin** [comment]
Nice job!
