### PR TITLE
[d3d8] Stub DebugSetMute to fix C&C:Generals performance

### LINKED ISSUE #4112: [d3d8] C&C: Generals/Zero Hour - menu slowdown
The game drops to ~15 fps when menus that are "heavy" on the UI like options or skirmish are accessed. This doesn't happen with WineD3D. The game is perfectly playable otherwise. Note that the game engine is capped at 31.2 fps.

The game and its addon are also available on Steam now, and are rather popular even these days, so we should look into this.

P.S.: The above problem is unaffected by cachedDynamicBuffers.

### Software information
C&C: Generals (& Zero Hour), retail.

### System information
- GPU: RTX 4070
- Driver: 535.183.01
- Wine version: 9.12 Staging
- DXVK version: fe9c875

### Apitrace file(s)
[generals.trace.tar.xz](https://drive.proton.me/urls/8XC0DHRN6M#YBYdw3mz1spl)

### Log files
- d3d8.log: [generals_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/11440472/generals_d3d8.log)

### PR DESCRIPTION
**Pull request by WinterSnowfall**
This has to be like the dumbest thing ever, but C&C: Generals is spamming calls to DebugSetMute() *every frame* whenever the slowdowns occur. Stubbing it makes it not choke. Fixes #4112.

### CODE REVIEW

File: src/d3d8/d3d8_main.cpp [hunk 1]
```diff
@@ -51,6 +51,10 @@ extern "C" {
     return S_OK;
   }
 
+  DLLEXPORT void __stdcall DebugSetMute() {
+    dxvk::Logger::debug("D3D8: DebugSetMute: Stub");
```
Comment (doitsujin) [inline src/d3d8/d3d8_main.cpp:55]: Can we make sure this is only logged once, especially if the game is spamming it?

**Review by doitsujin — COMMENTED** [review]
> This function is internal and not intended to be used by software developers.

Ah yeah, as if that has ever stopped anyone.

File: src/d3d8/d3d8_main.cpp (hunk 1 above)
Comment (WinterSnowfall) [reply src/d3d8/d3d8_main.cpp:55]: Can do, but I forgot how that was being done :sweat_smile: .

**Comment by netborg-afps** [comment]
Well to my understanding it does, as running the game through a simple wrapper on the pre-patch dxvk was solving this issue too, where DebugSetMute() was not defined.

**Comment by misyltoad** [comment]
because that wrapper stubs the function.

**Comment by netborg-afps** [comment]
No, it was my own experimental wrapper only defining Direct3DCreate8.
