### PR TITLE
[d3d8+9] Relax certain StretchRect restrictions

### LINKED ISSUE #4119: [d3d8] Phantasy Star Online Blue Burst broken reflection/animated texture effects regression
There's a small regression with the graphic effects used in reflection/refraction of surfaces that was previously fixed in this PR https://github.com/doitsujin/dxvk/pull/4015 which is affecting PSOBB again the latest dxvk with the d3d8 update. 

I tested this in both in Wine on my Desktop PC and also on my Steam Deck and both places displays the same issues. 

image

### Software information
Phantasy Star Online Blue Burst ver. 1.25.11 (official client)
client mirror [here](https://archive.org/details/psobb_jp_setup_12511_20240109)
test server patch [here](https://kiyomizu.moe/psobb/patch/PATCH_EN.zip)
(simply add wsock32 and psobb.cfg to the main game folder and add it as an
 override to winecfg, accounts are autocreated upon login) 

Windowed Mode
1280x920
high end setting

### Apitrace
[trace 1 seaside area](https://drive.google.com/file/d/10JEyMC7JMbKVDEbCDq2TotpN-RftCc3M/view?usp=sharing)
[trace 2 plant area](https://drive.google.com/file/d/1hUXxssZTXW8kfIKjzkFPGA3f2jXDFF7m/view?usp=sharing)

### System information
- GPU: RX6600
- Driver: Mesa 24.1.2 (Fedora 40)
- Wine version: 9.5 Staging
- DXVK version: the one available here https://github.com/doitsujin/dxvk/actions/runs/9826812319

### LINKED ISSUE #4122: [regression] AQUARIUM renders its FMV shortly into the game as a black screen
The first FMV partway into the game renders as a black screen. Previous behavior was that it played with visuals, albeit it may have had stutter. Using some prebuilt Proton builds, I narrowed it down to being after commit 1783b9591af787bc41dcdf8994158f67bb00fae5, and happening at or before commit bbe851f6a25b57f320362c97b12afc52bfa99da1

You can get to the FMV by starting a new game and holding down the left mouse button. This will fast forward through text. You will have to click on the screen once in the middle of fast forwarding to select a dialogue option. The one you select does not matter, and you can just left click anywhere on the screen to select the default.

### Software information
AQUARIUM (2515070), default settings.

### System information
- GPU: Nvidia 4070
- Driver: 535.183.01
- Failing Proton: experimental-bleeding-edge-9.0-106101-20240705-p4f856c-w8d6dce-dbbe851-v1a2f20
- Working Proton: experimental-bleeding-edge-9.0-106030-20240704-p4f856c-w8d6dce-d1783b9-v1a2f20

### Log files
[steam-2515070.log](https://github.com/user-attachments/files/16131833/steam-2515070.log)

### PR DESCRIPTION
**Pull request by K0bin**
Fixes #4119
Fixes #4122

I did some cleanup to CopyRects and put the StretchRect internals into a separate function that allows disabling specific checks.

cc
@WinterSnowfall 
@Joshua-Ashton

### CODE REVIEW

File: src/d3d9/d3d9_device.cpp [hunk 1]
```diff
@@ -1231,13 +1231,13 @@ namespace dxvk {
       if (unlikely(!srcIsDepth || !dstIsDepth))
         return D3DERR_INVALIDCALL;
 
-      if (unlikely(srcTextureInfo->Desc()->Discard || dstTextureInfo->Desc()->Discard))
+      if (unlikely((srcTextureInfo->Desc()->Discard || dstTextureInfo->Desc()->Discard) && StretchRectValidation))
```
Comment (WinterSnowfall) [inline src/d3d9/d3d9_device.cpp:1234]: Maybe just `!m_isD3D8compatible` here instead of StretchRectValidation, and avoid the entire wrapper mess?

**Comment by WinterSnowfall** [comment]
We should also probably change `unhandled()` to issue a `Logger:warn`, not just `debug`. From what I've seen so far there aren't any games out there to use CopyRects with SCRATCH, but if we do run across something like this it should be visible in the logs people send us. Pretty sure I changed this bit already, but must have gotten lost during upstreaming.

File: src/d3d9/d3d9_device.cpp [hunk 2]
```diff
@@ -1264,8 +1264,9 @@ namespace dxvk {
       // - both destination and source are depth stencil surfaces
       // - both destination and source are offscreen plain surfaces.
       // The only way to get a surface with resource type D3DRTYPE_SURFACE without USAGE_RT or USAGE_DS is CreateOffscreenPlainSurface.
-      if (unlikely(!dstHasRTUsage && (!dstIsSurface || !srcIsSurface || srcHasRTUsage)))
+      if (unlikely((!dstHasRTUsage && (!dstIsSurface || !srcIsSurface || srcHasRTUsage)) && StretchRectValidation)) {
```
Comment (WinterSnowfall) [inline src/d3d9/d3d9_device.cpp:1267]: Maybe just !m_isD3D8Compatible here instead of StretchRectValidation, and avoid the entire wrapper mess? Same for the rest of the disabled validations.

File: src/d3d9/d3d9_device.cpp [hunk 3]
```diff
@@ -1231,13 +1231,13 @@ namespace dxvk {
       if (unlikely(!srcIsDepth || !dstIsDepth))
         return D3DERR_INVALIDCALL;
 
-      if (unlikely(srcTextureInfo->Desc()->Discard || dstTextureInfo->Desc()->Discard))
+      if (unlikely((srcTextureInfo->Desc()->Discard || dstTextureInfo->Desc()->Discard) && StretchRectValidation))
         return D3DERR_INVALIDCALL;
 
-      if (unlikely(srcCopyExtent.width != srcExtent.width || srcCopyExtent.height != srcExtent.height))
+      if (unlikely((srcCopyExtent.width != srcExtent.width || srcCopyExtent.height != srcExtent.height) && StretchRectValidation))
```
Comment (WinterSnowfall) [inline src/d3d9/d3d9_device.cpp:1237]: Ditto

File: src/d3d9/d3d9_device.cpp [hunk 4]
```diff
@@ -1231,13 +1231,13 @@ namespace dxvk {
...
         return D3DERR_INVALIDCALL;
 
-      if (unlikely(m_flags.test(D3D9DeviceFlag::InScene)))
+      if (unlikely(m_flags.test(D3D9DeviceFlag::InScene) && StretchRectValidation))
```
Comment (WinterSnowfall) [inline src/d3d9/d3d9_device.cpp:1240]: Ditto

**Comment by WinterSnowfall** [comment]
We should also probably change `unhandled()` to issue a `Logger::warn`, not just `debug`. From what I've seen so far there aren't any games out there to use CopyRects with SCRATCH, but if we do run across something like this it should be visible in the logs people send us. Pretty sure I changed this bit already, but must have gotten lost during upstreaming.

**Comment by K0bin** [comment]
I simplified it like Winter suggested.

**Review by WinterSnowfall — APPROVED** [review]
I'd leave `logError()` on `debug`, since with some games failures of CopyRects aren't uncommon or unexpected. Otherwise LGTM.

**Comment by WinterSnowfall** [comment]
Also fixes a regression with Pure Pinball 2.0, but out of 140 d3d8 games only this one and Phantasy Star Online Blue Burst seem to abuse CopyRects/StretchRect to the point of hitting this validation.

**Comment by K0bin** [comment]
Before someone asks: No, it is not an option to flat out remove the checks I modified from StretchRect. There are Wine tests that test them.
