### PR TITLE
[d3d9] Do not set window size and position when restoring from fullscreen state

### LINKED ISSUE #2920: [d3d9] [regression] Fairy Fencer F borderless/windowed option makes game window disappear
Since https://github.com/doitsujin/dxvk/commit/cc11bb824045505439604d2bc1af9d805749ed09 in Fairy Fencer F when you click either the borderless or windowed option the game window disappears and can't be opened again. After some seconds it reappears since i can't confirm the new option selection.

### Software information
Fairy Fencer F started in fullscreen

### System information
- GPU: R9 380
- Driver: mesa  22.1.7
- Wine version: proton 7.0-4 and experimental
- DXVK version: https://github.com/doitsujin/dxvk/commit/cc11bb824045505439604d2bc1af9d805749ed09

### Log files
Log from bad commit
[FairyFencer_dxgi.log](https://github.com/doitsujin/dxvk/files/9568611/FairyFencer_dxgi.log)

Log from good commit
[FairyFencer_d3d9-good.log](https://github.com/doitsujin/dxvk/files/9568613/FairyFencer_d3d9-good.log)

### PR DESCRIPTION
**Pull request by gofman**
Closes #2920.

### CODE REVIEW

File: src/wsi/win32/wsi_window_win32.cpp [hunk 1]
```diff
@@ -211,11 +212,18 @@ namespace dxvk::wsi {
     }
 
     // Restore window position and apply the style
-    const RECT rect = pState->rect;
+    UINT swp_flags = SWP_FRAMECHANGED | SWP_NOACTIVATE;
```
Comment (Joshua-Ashton) [inline src/wsi/win32/wsi_window_win32.cpp:215]: Just call this flags.

File: src/wsi/win32/wsi_window_win32.cpp [hunk 2]
```diff
@@ -211,11 +212,18 @@ namespace dxvk::wsi {
...
+    RECT rect;
```
Comment (Joshua-Ashton) [inline src/wsi/win32/wsi_window_win32.cpp:216]: Any reason rect can't just always be `pState->rect` with SWP_NOSIZE and SWP_NOMOVE?

**Review by Joshua-Ashton — CHANGES_REQUESTED** [review]
nits

other than that, lgtm
