### PR TITLE
[d3d9] Handle mismatching vertex layout and vbo strides

### LINKED ISSUE #3919: [d3d9] Final Fantasy XIII (dxvk 2.3.1 regression?)
Going from DXVK version 2.3 to 2.3.1 artifacts / vertex explosion appeared. I think it's from 2d (font, hud,...) elements.

v.2.3
ff13-dxvk-v 2 3

v.2.3.1
ff13-dxvk-v 2 3 1

v.2.3
ff13-dxvk-v 2 3-ingame

v.2.3.1
ff13-dxvk-v 2 3 1-ingame

P.S.: Yes, DXVK HUD appears with `DXVK_HUD=full` , so it's using DXVK. In screenshots I only was using MANGOHUD.

### Software information
Final Fantasy XIII

### System information
- GPU: RTX 4080
- Driver: 550
- Wine version:  proton-8.0-5, proton-9-exp 
- DXVK version:  2.3 - 2.3.1

### Apitrace file(s)
https://drive.google.com/file/d/1kkeu1T3xLKVRgudiKBhJW1WZKkYNgBfg/view?usp=sharing
(made in linux/wine, I hope it's OK)

### Log files
[game.log](https://github.com/doitsujin/dxvk/files/14693907/game.log)

### PR DESCRIPTION
**Pull request by K0bin**
Fixes #3919

### CODE REVIEW

File: src/d3d9/d3d9_device.cpp [hunk 1]
```diff
@@ -5253,11 +5266,22 @@ namespace dxvk {
...
+        uint32_t offset = (BaseVertexIndex + FirstVertexIndex) * vboStride + m_state.vertexBuffers[i].offset;
 
         uint8_t* data = reinterpret_cast<uint8_t*>(upSlice.mapPtr) + vboUPBufferOffsets[i];
         uint8_t* src = reinterpret_cast<uint8_t*>(vbo->GetMappedSlice().mapPtr) + offset;
-        std::memcpy(data, src, vboUPBufferSizes[i]);
+        if (vertexStride == vboStride) {
+          std::memcpy(data, src, vboUPBufferSizes[i]);
+        } else {
+          const uint32_t vertexBufferSize = vbo->Desc()->Size;
+          const uint32_t boundVertexBufferRange = vertexBufferSize - offset;
```
Comment (Joshua-Ashton) [inline src/d3d9/d3d9_device.cpp:5278]: What if offset is > size?

File: src/d3d9/d3d9_device.cpp [hunk 2]
```diff
@@ -5202,13 +5202,26 @@ namespace dxvk {
...
-        vboUPBufferSizes[i] = vertexDataSize;
-        upBufferSize += vertexDataSize;
+
+      uint32_t vertexDataSize;
+      if (unlikely(vboOffset + vertexOffset > vertexBufferSize)) {
+        // All vertices are out of bounds
+        vertexDataSize = 0;
+      } else if (unlikely(vboOffset + vertexOffset + NumVertices * vboStride > vertexBufferSize)) {
+        // Some vertices are (partially) out of bounds
+        uint32_t boundVertexBufferRange = vertexBufferSize - vboOffset;
```
Comment (Joshua-Ashton) [inline src/d3d9/d3d9_device.cpp:5216]: Same here

**Comment by Joshua-Ashton** [comment]
This seems like a mess

**Comment by K0bin** [comment]
I pushed an updated version of this PR that should hopefully be a bit easier to read. It's still quite complex because we have to be robust against going out of bounds but it's a bit less messy now in my opinion.

File: src/d3d9/d3d9_device.cpp [hunk 3]
```diff
@@ -5240,30 +5273,34 @@ namespace dxvk {
...
-          ](DxvkContext* ctx) {
-            ctx->bindVertexBuffer(cStream, DxvkBufferSlice(), 0);
-          });
-          m_flags.set(D3D9DeviceFlag::DirtyVertexBuffers);
-          continue;
-        }
-
-        auto* vbo = GetCommonBuffer(m_state.vertexBuffers[i].vertexBuffer);
+        const VBOCopy& copy = vboCopies[i];
+        const auto* vbo = GetCommonBuffer(m_state.vertexBuffers[i].vertexBuffer);
```
Comment (PatrickvL) [inline src/d3d9/d3d9_device.cpp:5277]: This `vbo` variable could be moved inside below if block, to narrow its scope.

File: src/d3d9/d3d9_device.cpp [hunk 4]
```diff
@@ -5190,25 +5190,58 @@ namespace dxvk {
...
 
+    struct VBOCopy {
+      uint32_t srcOffset;
+      uint32_t dstOffset;
+      uint32_t copyBufferLength;
+      uint32_t copyElementCount;
+      uint32_t copyElementSize;
+      uint32_t copyElementStride;
+    };
     uint32_t upBufferSize = 0;
```
Comment (PatrickvL) [inline src/d3d9/d3d9_device.cpp:5201]: Usage of this variable implies it's a rolling value. Perhaps renaming it into `upBufferRollingSize` (or something comparable) would make this fact more clear. (Or perhaps there already is a naming convention in similar code that could be applied here too?)

File: src/d3d9/d3d9_device.cpp [hunk 5]
```diff
@@ -5190,25 +5190,58 @@ namespace dxvk {
...
-    std::array<uint32_t, caps::MaxStreams> vboUPBufferOffsets = {};
-    std::array<uint32_t, caps::MaxStreams> vboUPBufferSizes = {};
-    for (uint32_t i = 0; i < caps::MaxStreams && dynamicSysmemVBOs; i++) {
-      vboUPBufferOffsets[i] = upBufferSize;
+    std::array<VBOCopy, caps::MaxStreams> vboCopies = {};
 
+    for (uint32_t i = 0; i < caps::MaxStreams && dynamicSysmemVBOs; i++) {
```
Comment (PatrickvL) [inline src/d3d9/d3d9_device.cpp:5204]: In the other for loop over `caps.MaxStreams` below, the check on `dynamicSysmemVBOs` is done in a preceding `if`, not inside the if condition as happens here. 
Best to be consistent, so either move this loop inside an if block, or update below loop to follow the same approach as here.

File: src/d3d9/d3d9_device.cpp (hunk 4 above)
Comment (K0bin) [reply src/d3d9/d3d9_device.cpp:5201]: What's a rolling value?

`upBufferSize` just sums up the size of the vertex data for all vertex buffers and the index buffer so we can then allocate a single UpBuffer slice rather than needing multiple slices.

Comment (PatrickvL) [reply src/d3d9/d3d9_device.cpp:5201]: Indeed. It starts at zero and is incremented in each for loop iteration. 
Of course, to you it is probably obvious this is the way this works, but this usage can be seen as a pattern that happens elsewhere as well, and capturing that fact via a naming convention would make this clearer to a reader/maintainer of the code base.
Maybe "rolling" is not the most accurate terminology, perhaps something like "incremental" is the better word to describe this usage, but that's longer.
Feel free to ignore this reasoning, it's just a suggestion.

Comment (K0bin) [reply src/d3d9/d3d9_device.cpp:5201]: I could call it something like `totalUpBufferSize`. How about that?

File: src/d3d9/d3d9_device.cpp [hunk 6]
```diff
@@ -5190,25 +5190,58 @@ namespace dxvk {
...
-        upBufferSize += vertexDataSize;
+      const uint32_t srcOffset = vboOffset + vertexOffset;
+
+      if (unlikely(srcOffset > vertexBufferSize)) {
+        // All vertices are out of bounds
+        vboCopies[i].copyBufferLength = 0;
+      } else if (unlikely(srcOffset + elementCount * srcStride > vertexBufferSize)) {
+        // Some vertices are (partially) out of bounds
+        uint32_t boundVertexBufferRange = vertexBufferSize - vboOffset;
+        elementCount = boundVertexBufferRange / srcStride;
```
Comment (doitsujin) [inline src/d3d9/d3d9_device.cpp:5229]: what about the case where `stride > size` and the vbo size is something like `(n - 1) * stride + size`? All vertex data would be valid in that case.

**Review by doitsujin — APPROVED** [review]
