### PR TITLE
[d3d9] Disable fetch4 when binding an incompatible texture

### LINKED ISSUE #2780: Spider-man: Shattered Dimensions Lightning is messed up while using dxvk
### Its not a very major problem. I think the lightning of the game is messed up while using dxvk. The color of the suits are wrong.

I tried to do a trace but the game wouldn't run with the trace dll files. But it does run with dxvk d3d9.dll.

**Reports with no log files will be ignored.**

### Software information
Spider-man: Shattered Dimensions
32-bit
directx: 9.0c

### System information
- GPU: Radeon (TM) RX 480 Graphics
- Driver: 21.50.21.11-220428a-379219C-AMD-Software-Adrenalin-Edition
- Wine version: Using windows 10
- DXVK version: Latest version (dxvk 1.10.3)

### Apitrace file(s)
- Put a link here
the game wouldnt run with apitrace dlls

### Log files
- d3d9.log: [Game_d3d9.log](https://github.com/doitsujin/dxvk/files/9243830/Game_d3d9.log)

### Images

- Before using dxvk 

- After using dxvk

### PR DESCRIPTION
**Pull request by K0bin**
Fixes #2780

Curiously, this is pretty much the same issue as Black Mesa. The game ended up doing fetch4 with the lighting texture.
With Black Mesa I fixed it by restricting fetch4 to single channel formats, the problem was that I didn't disable fetch4 when binding an incompatible texture.

What a mess.

### CODE REVIEW

File: src/d3d9/d3d9_device.cpp [hunk 1]
```diff
@@ -3777,13 +3777,19 @@ namespace dxvk {
...
-        if (textureSupportsFetch4
+        if (unlikely(textureSupportsFetch4
           && m_state.samplerStates[StateSampler][D3DSAMP_MAGFILTER] == D3DTEXF_POINT
-          && m_state.samplerStates[StateSampler][D3DSAMP_MINFILTER] == D3DTEXF_POINT) {
+          && m_state.samplerStates[StateSampler][D3DSAMP_MINFILTER] == D3DTEXF_POINT
+          && !(m_fetch4 & (1u << StateSampler)))) {
+          // We swapped a multi channel texture for a single channel texture => turn on fetch4
           m_fetch4 |= 1u << StateSampler;
           m_dirtySamplerStates |= 1u << StateSampler;
+        } else if (unlikely(m_fetch4 & (1u << StateSampler))) {
```
Comment (Joshua-Ashton) [inline src/d3d9/d3d9_device.cpp:3789]: I don't think this else if is right? Either way, lets clean up this logic into separate bools, it's getting overly complex to follow at this point.

Comment (K0bin) [reply src/d3d9/d3d9_device.cpp]: Oh, you're right. I accidently dropped the format check when I added the comments.

**Comment by K0bin** [comment]
Tried to make this a bit more readable.

File: src/d3d9/d3d9_device.cpp [hunk 2]
```diff
@@ -3777,13 +3777,20 @@ namespace dxvk {
...
+        const bool samplerFetch4 = (m_fetch4 & (1u << StateSampler)) != 0;
+        const bool pointFilter = m_state.samplerStates[StateSampler][D3DSAMP_MAGFILTER] == D3DTEXF_POINT
+                                  && m_state.samplerStates[StateSampler][D3DSAMP_MINFILTER] == D3DTEXF_POINT;
+        const bool textureSupportsFetch4 = newTexture->SupportsFetch4();
+
+        if (unlikely(textureSupportsFetch4 && pointFilter && !samplerFetch4)) {
+          // We're swapping a multi channel texture for a single channel texture => turn on fetch4
           m_fetch4 |= 1u << StateSampler;
           m_dirtySamplerStates |= 1u << StateSampler;
+        } else if (unlikely(!textureSupportsFetch4 && samplerFetch4)) {
```
Comment (Joshua-Ashton) [inline src/d3d9/d3d9_device.cpp:3790]: Looks like we don't disable it if we go from point filter enabled -> point filter disabled?

Probably wants to be `!(textureSupportsFetch4 && pointFilter) && samplerFetch4`?

I would just add another bool for `supported` at that point.

File: src/d3d9/d3d9_device.cpp [hunk 3]
```diff
@@ -3777,13 +3777,20 @@ namespace dxvk {
...
       }
 
-      if (unlikely(m_fetch4Enabled & (1u << StateSampler) && !(m_fetch4 & (1u << StateSampler)))) {
-        bool textureSupportsFetch4 = newTexture->SupportsFetch4();
-        if (textureSupportsFetch4
-          && m_state.samplerStates[StateSampler][D3DSAMP_MAGFILTER] == D3DTEXF_POINT
-          && m_state.samplerStates[StateSampler][D3DSAMP_MINFILTER] == D3DTEXF_POINT) {
+      if (unlikely(m_fetch4Enabled & (1u << StateSampler))) {
+        const bool samplerFetch4 = (m_fetch4 & (1u << StateSampler)) != 0;
+        const bool pointFilter = m_state.samplerStates[StateSampler][D3DSAMP_MAGFILTER] == D3DTEXF_POINT
```
Comment (Joshua-Ashton) [inline src/d3d9/d3d9_device.cpp:3782]: && at the end pls

Comment (pchome) [reply src/d3d9/d3d9_device.cpp:3782]: But in most cases && used like in this random place:
```cpp
    useSubgroupOpsForEarlyDiscard
       = (devInfo.vk11.subgroupSize >= 4)
      && (devInfo.vk11.subgroupSupportedStages & VK_SHADER_STAGE_FRAGMENT_BIT)
      && (devInfo.vk11.subgroupSupportedOperations & VK_SUBGROUP_FEATURE_BALLOT_BIT);
```

Comment (K0bin) [reply src/d3d9/d3d9_device.cpp:3782]: I personally prefer the && in front too.

**Comment by Joshua-Ashton** [comment]
I changed my mind, I prefer this than my other solution, meh.
