### PR TITLE
[d3d9] Only upload mip 0 of managed automipgen textures

### LINKED ISSUE #3058: Supreme Commander: Forged Alliance crash after loading screen
The game crashes immediately after the loading screen (appears to be segmentation fault) on dxvk 2.0. dxvk 1.10.3 does not have this issue.

I did a `git bisect` and the commit https://github.com/doitsujin/dxvk/commit/d8933ca175aac5598cc6abf3ea5384553c5f01b4 appears to be the issue. Reverting this commit on latest master (8f8a93696d36adca8efeed4e16dc6b3deea27268) fixes the issue. 

Unfortunately I can't seem to get any debugger to actually work.

### Software information
Supreme Commander: Forged Alliance (Steam appid 9420 and FAF versions both crash)
Graphics API: d3d9

### System information
- GPU: Intel i7-12700h integrated graphics (ADL GT2)
- Driver: Mesa 22.1.7 (`iris`), kernel 6.1.0-rc3+
- Wine version: Proton Experimental (`wine-7.0`)
- DXVK version: 2.0

### Apitrace files
Apitrace hangs on both dxvk and wined3d. Not sure how to obtain.

### Log files
- d3d9.log: [ForgedAlliance_d3d9.log](https://github.com/doitsujin/dxvk/files/9996477/ForgedAlliance_d3d9.log)

### PR DESCRIPTION
**Pull request by K0bin**
Fixes #3058

I really hate automatic mipmap generation.

We currently upload the non 0 mip maps even though those can't be locked.

### CODE REVIEW

File: src/d3d9/d3d9_common_texture.h [hunk 1]
```diff
@@ -373,14 +373,14 @@ namespace dxvk {
       m_needsUpload.setAll();
     }
     void SetNeedsUpload(UINT Subresource, bool upload) { m_needsUpload.set(Subresource, upload); }
-    bool NeedsUpload(UINT Subresource) const { return m_needsUpload.get(Subresource); }
+    bool NeedsUpload(UINT Subresource) const { return m_needsUpload.get(Subresource) && (Subresource / m_desc.ArraySize) < ExposedMipLevels(); }
```
Comment (Joshua-Ashton) [inline src/d3d9/d3d9_common_texture.h:376]: Shouldn't this be % based on CalcSubresource?

Comment (Joshua-Ashton) [reply src/d3d9/d3d9_common_texture.h:376]:
```
    UINT CalcSubresource(UINT Face, UINT MipLevel) const {
      return Face * m_desc.MipLevels + MipLevel;
    }
```

**Comment by Joshua-Ashton** [comment]
I'd prefer it if we moved this check to whatever is calling SetNeedsUpload rather than here.
