### PR TITLE
[util] Enable d3d9.memoryTrackTest for The Ship

### LINKED ISSUE #2893: [d3d9] The Ship(2400) uses up all virtual memory and GPU memory and then crash
After launch, the game gradually uses up virtual memory and GPU memory and then crashes, both on Proton 7.0 and on Windows 11. Even though the game is 32bit, it manages to use up 8G dedicated GPU memory and 8G shared GPU memory. And finally, running out of GPU memory, the game crashes. On Wine, the virtual memory limit is hit first and crashes. With native d3d9 on Windows or wined3d on Proton 7.0-4, the game runs normally. On Proton, you need to turn off the fullscreen hack first to get around its bugs.

### Software information
The Ship (SteamID: 2400)

### System information
- GPU: AMD RX5500 8G
- Driver: 30.0.15021.11005(AMD driver on Windows)
- Wine version: Wine 7.0
- DXVK version: 1.10.3

### Apitrace file(s)
[ship_d3d9_trace.zip](https://github.com/doitsujin/dxvk/files/9504077/ship_d3d9_trace.zip)

### Log files
- d3d9.log:[ship_d3d9.log](https://github.com/doitsujin/dxvk/files/9504074/ship_d3d9.log)

### PR DESCRIPTION
**Pull request by K0bin**
Fixes #2893

I think we should ship this.

### CODE REVIEW

File: src/util/config/config.cpp [hunk 1]
```diff
@@ -602,6 +602,10 @@ namespace dxvk {
       { "d3d9.memoryTrackTest",             "True" },
       { "d3d9.maxAvailableMemory",          "2048" },
     }} },
+    /* The Ship (2004)                          */
+    { R"(\\shop\.exe$)", {{
```
Comment (Blisto91) [inline src/util/config/config.cpp:606]:
```suggestion
    { R"(\\ship\.exe$)", {{
```

Comment (K0bin) [reply src/util/config/config.cpp]: .___.

**Review by Blisto91 — APPROVED** [review]

**Comment by alasky17** [comment]
@K0bin @Blisto91 @doitsujin This is another one that would be great to get in the 1.10.x branch :).
