### PR TITLE
[d3d9] Rework FF texcoord processing

### LINKED ISSUE #4035: World of Warcraft 1.12: regression caused by 7df8017
The [7df8017](https://github.com/doitsujin/dxvk/commit/7df8017e46692e972c710435261950c941b03acd) commit from yesterday renders all earth in vanilla World of Warcraft 1.12 reflecting: https://youtu.be/FE3w5zxD4_Y

Its parent commit is good.

### Software information
World of Warcraft 1.12 vanilla (Turtle server: https://turtle-wow.org/)

### System information
- GPU:
Firstly witnessed the bug on AMD RX7900XTX on Mesa 24.0.7
The API trace was made on NVIDIA GeForce MX150 on 551.23 Windows driver (Same bug occur on this platform either)

- Driver:
Mesa 24.0.7 with linux-image-6.8.11-1-liquorix-amd64
NVIDIA 551.23 Windows driver

- Wine version: 
GE-Proton9-5
Windows 11 (21H2)

- DXVK version: 
[7df8017](https://github.com/doitsujin/dxvk/commit/7df8017e46692e972c710435261950c941b03acd) 

### Apitrace file(s)
- https://drive.google.com/file/d/1GqQ0lZJcYGl1FG5gMhleINnAlfKA9aZa/view?usp=sharing

### LINKED ISSUE #4087: C&c generals zhor bug on dxvk+d8vk
Screenshot_2024-06-23-15-05-41-373_com ludashi benchmark
On turnip android

### PR DESCRIPTION
**Pull request by K0bin**
Fixes #4035
Fixes #4087 

We need to apply the count **after** transforming the texcoord.

Passes my tests here: https://gitlab.winehq.org/K0bin/wine/-/blob/ff-texcoord-tests/dlls/d3d9/tests/visual.c#L28402-29023

### CODE REVIEW

**Review by doitsujin — APPROVED** [review]
d3d9 sure is something, huh

**Comment by allfoxwy** [comment]
I think this fix is working. Thanks for quick response!

File: src/d3d9/d3d9_fixed_function.h [hunk 1]
```diff
@@ -133,6 +133,8 @@ namespace dxvk {
         uint32_t VertexBlendCount   : 3;
 
         uint32_t VertexClipping     : 1;
+
+        uint8_t Projected;
```
Comment (Joshua-Ashton) [inline src/d3d9/d3d9_fixed_function.h:137]: You didn't pack this or update primitive.

**Comment by K0bin** [comment]
It passes all the upstream Wine tests and I ran it through all games that are known to be affected by ff texcoord processing:
- WoW
- ColdFear
- Phantasy Star Online (both apitraces)
- Snowblind

Needs to be tested:
- Command & Conquer Generals
- Total War Rome

**Comment by Blisto91** [comment]
Both Command & Conquer Generals and Total War Rome looks good
